spring:
  dataSource:
    url: jdbc:h2:file:C:\\Users\\juan.ssantos3\\Downloads\\rest\\database.db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: "ANT_PATH_MATCHER"
    h2:
      console.enable: true
      console:
        path: /h2-console
        settings.trace: true
        settings.web-allow-others: false
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.ddl-auto: create
      defer-datasource-initialization: true